name: Model Auto-tracing & Uploading
on:
  workflow_dispatch:
    inputs:
      model_name:
        description: "Name of the model to auto-trace and upload"
        required: true
        type: string

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:        
        cluster: ["opensearch"]        
        secured: ["true"]        
        entry:          
          - { opensearch_version: 2.7.0 }

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'     
      - name: Install dependencies       
        run: python3 -m pip install opensearch-py-ml   
      - name: Autotrace and Upload           
        run: python3 auto_script.py
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated models" --allow-empty)
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: git-action
