name: Test-Workflow
on:
  workflow_dispatch:
    inputs:
      test_input:
        description: "Test Input"
        required: true
        type: string

jobs:
  model-autotracing:
    name: model-tracing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cluster: ["opensearch"]
        secured: ["true"]
        entry:
          - { opensearch_version: 2.7.0 }
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Create Files
        run: |
          mkdir -p ./upload/test_folder_1/test_folder_2
          echo "Test Input=${{ github.event.inputs.test_input }}" >> upload/test_folder_1/test_folder_2/test_file.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with: 
          name: upload
          path: ./upload/

  manual-approval:
    needs: model-autotracing
    runs-on: 'ubuntu-latest'
    permissions:
      issues: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - id: get_approvers
        run: |
          echo "approvers=$(cat .github/CODEOWNERS | grep @ | tr -d '* ' | sed 's/@/,/g' | sed 's/,//1')" >> $GITHUB_OUTPUT
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ steps.get_approvers.outputs.approvers }}
          minimum-approvals: 1
          issue-title: 'Upload opensearch-py-ml model to Amazon S3 Bucket'
          issue-body: "Please approve or deny opensearch-py-ml model uploading: ${{ github.event.inputs.test_input }}"
          exclude-workflow-initiator-as-approver: false
      
  model-uploading:
    needs: manual-approval
    runs-on: 'ubuntu-latest'
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: upload
          path: ./upload/
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ secrets.MODEL_UPLOADER_AWS_REGION }}
          role-to-assume: ${{ secrets.MODEL_UPLOADER_ROLE }}
          role-session-name: GitHubActions
      - name: Copy files to the bucket
        run: |
          aws s3 sync ./upload/ s3://opensearch-exp/
