name: Model Auto-tracing & Uploading
on:
  workflow_dispatch:
    inputs:
      model_id:
        description: "Model ID for auto-tracing and uploading (e.g. sentence-transformers/msmarco-distilbert-base-tas-b)"
        required: true
        type: string
      model_version:
        description: "Model version number (e.g. 1.0.1)"
        required: true
        type: string
      tracing_format:
        description: "Model format for auto-tracing (torch_script/onnx)"
        required: true
        type: choice
        options:
        - "BOTH"
        - "TORCH_SCRIPT"
        - "ONNX"
      embedding_dimension:
        description: "(Optional) Embedding Dimension (Specify here if it does not exist in original config.json file. Else, it will use 768)"
        required: false
        type: int
      pooling_mode:
        description: "(Optional) Pooling Mode (Specify here if it does not exist in original config.json file)"
        required: false
        type: choice
        options:
        - ""
        - "CLS"
        - "MEAN"
        - "MAX"
        - "MEAN_SQRT_LEN"

jobs:
 manual-approval:
    runs-on: 'ubuntu-latest'
    permissions:
      issues: write 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Get Approvers
        id: get_approvers
        run: |
          echo "approvers=$(cat .github/CODEOWNERS | grep @ | tr -d '* ' | sed 's/@/,/g' | sed 's/,//1')" >> $GITHUB_OUTPUT
      - name: Create Issue Body
        id: create_issue_body
        run: |
          issue_body="Please approve or deny opensearch-py-ml model uploading:\n
                      - Workflow Initiator: @${{ github.actor}}\n
                      - Model ID: ${{ github.event.inputs.model_id }}\n
                      - Model Version: ${github.event.inputs.model_version}\n
                      - Tracing Format: ${{ github.event.inputs.tracing_format }}\n
                      - Embedding Dimension: ${{ github.event.inputs.embedding_dimension }}\n
                      - Pooling Mode: ${{ github.event.inputs.pooling_mode }}"
          issue_body="${issue_body//'%'/'%25'}"
          issue_body="${issue_body//$'\n'/'%0A'}"
          issue_body="${issue_body//$'\r'/'%0D'}"
          echo "issue_body=$issue_body" >> $GITHUB_OUTPUT
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ steps.get_approvers.outputs.approvers }}
          minimum-approvals: 1
          issue-title: "Upload opensearch-py-ml model to Amazon S3 Bucket (${{ github.event.inputs.model_id }})"
          issue-body: ${{ steps.create_issue_body.issue_body }}
          exclude-workflow-initiator-as-approver: false
          

