name: Test uploading outputs to JSON
on:
  workflow_dispatch:
    inputs:
      model_id:
        description: "Model ID for auto-tracing and uploading (e.g. sentence-transformers/msmarco-distilbert-base-tas-b)"
        required: true
        type: string
jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cluster: ["opensearch"]
        secured: ["true"]
        entry:
          - { opensearch_version: 2.7.0 }
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: python3 -m pip install opensearch-py-ml
      - name: Autotrace and Upload
        run: |
          echo "Model ID:" ${{ github.event.inputs.model_id }}
          python3 automated_actions/pass_outputs.py automated_actions/output_dict.json ${{ github.event.inputs.model_id }}
      - name: Save folder path
        run: |
          echo "FOLDER_PATH=$(jq '.folder_path' automated_actions/output_dict.json)" >> $GITHUB_ENV
      - name: Echo folder path
        run: |
          echo "${{ env.FOLDER_PATH }}"
          mkdir "upload"
          echo "${{ env.FOLDER_PATH }}" >> "output.txt"
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: "output.txt"
      - name: Upload JSON
        uses: actions/upload-artifact@v3
        with:
          path: "automated_actions/output_dict.json"
      - name: Upload to Bucket
        uses: hkusu/s3-upload-action@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-west-2'
          aws-bucket: ${{ secrets.AWS_BUCKET }}
          file-path: 'output.txt'     
