name: Update Model Listing
on:
  workflow_dispatch:
  
  
jobs:
  update-model-listing:
    runs-on: 'ubuntu-latest'
    permissions:
      id-token: write
      contents: read
    steps:
    - name: List models
      run: |
          model_lists=$(aws s3api list-objects --bucket ${{ secrets.PERSONAL_MODEL_BUCKET }} > /dev/null 2>&1)
          echo $model_lists
    - name: List models II
      run: |
          aws s3api list-objects --bucket ${{ secrets.PERSONAL_MODEL_BUCKET }} > /dev/null 2>&1
          
