name: Update Model Listing
on:
  workflow_dispatch:
  
  
jobs:
  update-model-listing:
    runs-on: 'ubuntu-latest'
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ${{ secrets.PERSONAL_MODEL_UPLOADER_AWS_REGION }}
        role-to-assume: ${{ secrets.PERSONAL_MODEL_UPLOADER_ROLE }}
        role-session-name: update-model-listing
    - name: List models
      run: |
          model_lists=$(aws s3api list-objects --bucket ${{ secrets.PERSONAL_MODEL_BUCKET }} --prefix "ml-models/huggingface/sentence-transformers/" --query "Contents[].{Key: Key}" --output json)
          echo $model_lists
          
