name: Update Model Listing
on:
  workflow_dispatch:
  
  
jobs:
  update-model-listing:
    runs-on: 'ubuntu-latest'
    permissions:
      id-token: write
      contents: read
    steps:
    - name: List models
      run: |
          model_lists=$(aws s3 ls s3://${{ secrets.PERSONAL_MODEL_BUCKET }} --recursive | awk '{print $4}')
          echo $model_lists
