name: Update Model Listing
on:
  workflow_dispatch:
  
  
jobs:
  update-model-listing:
    runs-on: 'ubuntu-latest'
    permissions:
      id-token: write
      contents: read
    steps:
    - name: List models
      run: |
          model_lists=$(aws s3api list-objects --bucket "bucket" --prefix "foo/" --query "Contents[].{Key: Key}" --output text)
          echo $model_lists
