name: Update Model Listing
on:
  workflow_dispatch: # TO-BE-CHANGED

jobs:
  update-model-listing:
    runs-on: 'ubuntu-latest'
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ${{ secrets.PERSONAL_MODEL_UPLOADER_AWS_REGION }}
        role-to-assume: ${{ secrets.PERSONAL_MODEL_UPLOADER_ROLE }}
        role-session-name: update-model-listing
    - name: List models
      run: |
        aws s3api list-objects --bucket ${{ secrets.PERSONAL_MODEL_BUCKET }} --prefix "ml-models/huggingface/" --query "Contents[].{Key: Key}" --output text) >> utils/model_uploader/current_models.txt
        aws s3 cp s3://${{ secrets.PERSONAL_MODEL_BUCKET }}/model_listing/pre_trained_models.json  utils/model_uploader/old_pre_trained_models.json
    - name: Create new pre_trained_models.json
      run: | 
        python create_new_trained_model_listing.py # TODO: Write python file to save file to new_pre_trained_models.json
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with: 
        name: upload
        path: |
          utils/model_uploader/old_pre_trained_models.json
          utils/model_uploader/new_pre_trained_models.json
        retention-days: 5
        if-no-files-found: error
    - name: Update new pre_trained_models.json in S3
      run: aws s3 cp utils/model_uploader/new_pre_trained_models.json s3://${{ secrets.PERSONAL_MODEL_BUCKET }}/model_listing/pre_trained_models.json
      
        
# TODO: Trigger Jenkins Workflow
